apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    appname: busybox-105
  name: busybox-105
spec:
  selector:
    matchLabels:
      workload: busybox-105
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        workload: busybox-105
    spec:
      containers:
      - command:
        - sh
        - -c
        - while true; do echo $(date); dd if=/dev/urandom bs=1024 count=10240 of=/mnt/test/mbr.img oflag=append conv=notrunc; sync; sleep 1; done
        image: quay.io/vcppds7878/busybox:latest
        imagePullPolicy: IfNotPresent
        name: busybox
        volumeMounts:
        - mountPath: /mnt/test
          name: mypvc
      volumes:
      - name: mypvc
        persistentVolumeClaim:
          claimName: busybox-pvc-105
          readOnly: false
